credentials : 
  Oauth : "y0_AgAAAABwYXHYAApqHQAAAADrcCoiPOZhnJe_QuSfyrAipHv03L3lXJ8"
  base_url : "https://cloud-api.yandex.net/v1/disk"

pages :
  resourses :
    base : "/resources?path="
    application : "/resources?path=%2F"
    copy : "/resources/copy"
    download : "/resources/download" 
    files : "/resources/files"
    last_upload : "/resources/last_upload"
    move : "/resources/move"
    public : "/resources/public"
    publish : "/resources/publish"
    unpublish : "/resources/unpublish"
    upload : "/resources/upload"
    restore : "/resources/restore"

headers : 
  "Content-Type": "application/json"
  "Accept": "application/json"
  "Authorization": "OAuth"

user: 
      reg_time: "2023-08-29T08:55:40+00:00"
      display_name: "TestUi001"
      uid: "1885434328"
      country: "ru"
      is_child: false 
      login: "TestUi001"

number_iter : 3